// <auto-generated />
using Indexing.Infra.SqLite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Indexing.Infra.SqLite.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Indexing.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Age");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<double?>("Salary");

                    b.Property<decimal?>("Score");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Indexing.Domain.Entities.Employee", b =>
                {
                    b.OwnsOne("Indexing.Domain.Entities.Address", "FullAddress", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId");

                            b1.Property<string>("Street")
                                .HasColumnName("Street")
                                .HasMaxLength(250);

                            b1.Property<string>("ZipCode")
                                .HasColumnName("ZipCode")
                                .HasMaxLength(10);

                            b1.ToTable("Employees");

                            b1.HasOne("Indexing.Domain.Entities.Employee")
                                .WithOne("FullAddress")
                                .HasForeignKey("Indexing.Domain.Entities.Address", "EmployeeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
